### ISSUE TITLE
I/O error when accessing the API

### ISSUE THREAD

**Issue by goneall** [OpenSourceOrg/api#20]
Recently, we started getting I/O errors when accessing the API.

The specific error returned is `java.security.cert.CertificateException: No subject alternative DNS name matching api.opensource.org found.`

This will impact the SPDX license list's ability to mark the OSI URL's as active.

See the [LicenseListPublisher PR 155](https://github.com/spdx/LicenseListPublisher/pull/155) comments for more context.

**Comment by debbryant** [comment]
Unclear if anyone responded to your email, notifying stakeholders by CC if this has been missed; we recently did a major web site migration and will check to see if something was broken.  Apologies for the extra traffic if this has already been resolved.

Deb Bryant

**Comment by smaffulli** [comment]
@goneall this issue was due to the DNS switch when we moved the website to a new host. It should be resolved now, API has its own, proper DNS record now. Can you please confirm?

**Comment by goneall** [comment]
@smaffulli It has improved but not completely fixed.  I can now successfully access the API from my local machine, but when I run it in a GitHub action, I'm still getting a failure.  I recall we had this issue before - I think there was a firewall blocking the GitHub based access to the API.
